# Generated by Django 5.2.4 on 2025-07-03 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=50)),
                ('numero_alumnos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion_breve', models.TextField()),
                ('areas_curriculares', models.CharField(max_length=200)),
                ('duracion_sesiones', models.IntegerField()),
                ('contenido_completo', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('diagnostico', models.CharField(blank=True, max_length=200, null=True)),
                ('caracteristicas', models.TextField(blank=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aula')),
            ],
        ),
    ]
