# Generated by Django 5.2.4 on 2025-07-03 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_proyecto_adaptaciones_aacc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='objetivos',
            field=models.TextField(blank=True),
        ),
    ]
